/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        paper: "#FFFFFF",
        canvas: "#F7F8FA",
        ink: "#101828",
        inkfaint: "#667085",
        line: "#EAECF0",
        lineStrong: "#D0D5DD",
        lilac: "#F0EEFF",
        lilacDeep: "#5447C8",
        sage: "#ECFDF3",
        sageDeep: "#15803D",
        peach: "#FFF7E8",
        peachDeep: "#B45309",
        sky: "#EEF8FF",
        skyDeep: "#0369A1",
        flare: "#635BFF",
        flareDeep: "#4F46E5",
        flareSoft: "#F0EEFF",
        success: "#16A34A",
        successSoft: "#ECFDF3",
        danger: "#B42318",
        dangerSoft: "#FEF3F2",
        shell: "#101828",
        shellLine: "#344054",
        shellFaint: "#98A2B3",
      },
      fontFamily: {
        display: ["SpaceGrotesk_700Bold"],
        displayMed: ["SpaceGrotesk_500Medium"],
        body: ["Inter_400Regular"],
        bodyMed: ["Inter_500Medium"],
        mono: ["JetBrainsMono_500Medium"],
      },
    },
  },
  plugins: [],
};
